# Generated by Django 3.2.12 on 2024-08-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('DA', 'Daily'), ('WE', 'Weekly'), ('MO', 'Monthly'), ('YE', 'Yearly')], max_length=2, null=True),
        ),
    ]
