# Generated by Django 5.1 on 2024-08-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='category',
            field=models.CharField(choices=[('choose', 'Choose a Category'), ('electronics', 'Electronics'), ('books', 'Books'), ('clothing', 'Clothing'), ('home', 'Home & Kitchen'), ('toys', 'Toys & Games'), ('sports', 'Sports & Outdoors'), ('beauty', 'Beauty & Personal Care'), ('other', 'Other')], default='choose', max_length=50),
            preserve_default=False,
        ),
    ]
