# Generated by Django 5.1 on 2024-08-26 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='visible_to_friends',
        ),
    ]
