from django.urls import path
from .views import (
    RegisterView,
    UserProfileView,
    LoginView,
    LogoutView,
    RefreshTokenView,
    EventListCreate,
    OwnEventListView,
    FriendEventListView,
    OwnEventRetrieveView,
    FriendEventRetrieveView,
    EventRetrieveUpdateDestroy,
    OwnWishlistRetrieveUpdateDestroyView,
    OwnWishlistItemCreateView,
    OwnWishlistItemRetrieveUpdateDestroyView,
    FriendWishlistRetrieveView,
    FriendshipRequestCreate,
    FriendshipListView,
    FriendshipDeleteView,
    NotificationListView,
    NotificationRetrieveDestroyView
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('token/refresh/', RefreshTokenView.as_view(), name='token_refresh'),
    path('events/', EventListCreate.as_view(), name='event-list-create'),
    path('events/own/', OwnEventListView.as_view(), name='own-event-list'),
    path('events/friend/<int:friend_id>/', FriendEventListView.as_view(), name='friend-event-list'),
    path('events/own/<int:pk>/', OwnEventRetrieveView.as_view(), name='own-event-retrieve'),
    path('events/friend/<int:friend_id>/<int:pk>/', FriendEventRetrieveView.as_view(), name='friend-event-retrieve'),
    path('wishlists/me/', OwnWishlistRetrieveUpdateDestroyView.as_view(), name='own-wishlist'),
    path('wishlists/me/items/add/', OwnWishlistItemCreateView.as_view(), name='own-wishlist-item-create'),
    path('wishlists/me/items/<int:pk>/', OwnWishlistItemRetrieveUpdateDestroyView.as_view(), name='own-wishlist-item'),
    path('wishlists/friend/<int:friend_id>/', FriendWishlistRetrieveView.as_view(), name='friend-wishlist'),
    path('events/<int:pk>/', EventRetrieveUpdateDestroy.as_view(), name='event-retrieve-update-destroy'),
    path('friendships/', FriendshipRequestCreate.as_view(), name='friendship-request-create'),
    path('friendships/list/', FriendshipListView.as_view(), name='friendship-list'),
    path('friendships/delete/<int:to_user_id>/', FriendshipDeleteView.as_view(), name='friendship-delete'),
    path('notifications/', NotificationListView.as_view(), name='notification-list'),
    path('notifications/<int:pk>/', NotificationRetrieveDestroyView.as_view(), name='notification-retrieve-destroy'),
]
